### ISSUE TITLE
Gene Ontology annotations for RNAs

### ISSUE THREAD

**Issue by justaddcoffee** [AnacletoLAB/RNA-KG#1]
Per convo with Chris Mungall, there is abundant GO annotations for lots of human RNAs. We can help set up an ingest for these if this is of interest (and you are not already ingesting them)

**Comment by emanuelecavalleri** [comment]
Hi Justin! Thanks for reaching out, this would be very interesting! I will send an email to you and Chris to schedule a meeting😃
